site_name: ostis-example-app
dev_addr: 127.0.0.1:8005
repo_url: https://github.com/ostis-apps/ostis-example-app

extra_css:
  - _assets/main.css

extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js

nav:
  - Home: index.md
  - C++ agents:
    - Path Finding Agent: agents/path_finding_agent.md
  - License: https://github.com/ostis-apps/ostis-example-app/blob/0.10.0/LICENSE

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'

theme:
  name: material
  favicon: _assets/ostis-logo.png
  logo: _assets/ostis-logo.png
  palette:  # Defines color schemes for light and dark modes
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant       # Enables instant loading of pages
    - navigation.tracking      # Automatically focuses active section in sidebar
    - navigation.tabs          # Adds top-level sections as tabs
    - navigation.sections      # Renders top-level sections as groups in sidebar
    - navigation.expand        # Expands all collapsible sections by default
    - navigation.top           # Adds a "back to top" button
    - search.suggest           # Displays search suggestions
    - search.highlight         # Highlights search terms on result page
    - content.action.edit      # Adds links to edit doc files
    - content.tabs.link        # Shares link when clicking on a tab
    - content.code.copy        # Adds a copy button to code blocks

markdown_extensions:
  - admonition                 # Allows creation of call-out boxes (e.g., notes, warnings)
  - codehilite
  - md_in_html                 # Allows Markdown syntax inside HTML blocks
  - pymdownx.highlight:        # Enhances code block highlighting
      anchor_linenums: true
  - pymdownx.inlinehilite      # Enables inline code highlighting
  - pymdownx.details           # Allows creating collapsible elements
  - pymdownx.superfences       # Enables advanced fenced code blocks
